### ISSUE TITLE
Lack of unit tests for the project

### ISSUE THREAD

**Issue by Mookel** [alibaba/xoc#7]
I am not sure wether this is the right place to ask, my questions is: why there are not any unit tests for this project, how to ensure the correctness of the ir??

**Comment by stevenknown** [comment]
Please move to https://github.com/stevenknown/xgen. That is a complete project to use XOC, and there is a testsuite both for C language and IR builder.

**Comment by Mookel** [comment]
> Please move to https://github.com/stevenknown/xgen. That is a complete project to use XOC, and there is a testsuite both for C language and IR builder.

Well noted @stevenknown , I will move to the xgen project, thanks very much.
